// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfkvplkhTOtoaxlsqlCiTi2sxnb2AQMF8',
    appId: '1:1011880412752:web:074735f35ddad1631d7355',
    messagingSenderId: '1011880412752',
    projectId: 'chatingapp-2648d',
    authDomain: 'chatingapp-2648d.firebaseapp.com',
    storageBucket: 'chatingapp-2648d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlRAFrg8lO0TJGJnOIvvBSvbfXJiCBf5s',
    appId: '1:1011880412752:android:96136963eec3cafc1d7355',
    messagingSenderId: '1011880412752',
    projectId: 'chatingapp-2648d',
    storageBucket: 'chatingapp-2648d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgWtP1L7X24j41R9BAtHr0GAlRDFHFSw4',
    appId: '1:1011880412752:ios:49baba9b75c507371d7355',
    messagingSenderId: '1011880412752',
    projectId: 'chatingapp-2648d',
    storageBucket: 'chatingapp-2648d.firebasestorage.app',
    iosBundleId: 'com.example.chtapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgWtP1L7X24j41R9BAtHr0GAlRDFHFSw4',
    appId: '1:1011880412752:ios:49baba9b75c507371d7355',
    messagingSenderId: '1011880412752',
    projectId: 'chatingapp-2648d',
    storageBucket: 'chatingapp-2648d.firebasestorage.app',
    iosBundleId: 'com.example.chtapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfkvplkhTOtoaxlsqlCiTi2sxnb2AQMF8',
    appId: '1:1011880412752:web:ef06994bbbcd2ef21d7355',
    messagingSenderId: '1011880412752',
    projectId: 'chatingapp-2648d',
    authDomain: 'chatingapp-2648d.firebaseapp.com',
    storageBucket: 'chatingapp-2648d.firebasestorage.app',
  );
}
